[provider]
USE_GROQ=true
USE_OPENAI=false
USE_HF=false

GROQ_ENDPOINT='https://api.groq.com/openai/v1/'
OPENAI_ENDPOINT='https://api.openai.com/v1/'
HF_ENDPOINT='https://api-inference.huggingface.co/models/'