[provider]
USE_GROQ=false
USE_OPENAI=false
USE_HF=true

GROQ_ENDPOINT='https://api.groq.com/openai/v1/'
OPENAI_ENDPOINT='https://api.openai.com/v1/'
HF_ENDPOINT='https://router.huggingface.co/hf-inference/v1'